# Generated by Django 4.0.6 on 2022-07-30 11:28

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_date_created_comment_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title_image_url',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_to),
        ),
    ]
