# Generated by Django 4.0.6 on 2022-07-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blog_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='blog count'),
        ),
    ]
